### ISSUE TITLE
Booking.com - Privacy Policy is blinking

### ISSUE THREAD

**Issue by martinratinaud** [OpenTermsArchive/contrib-declarations#559]
This is due to the fact that snapshots shows content is changing from one snapshot to another

First snapshot

```
<link rel="help" href="/faq.en-gb.html?label=<label>&sid=<sid>&amp;" />
```

Second snapshot

```
<link rel="help" href="/faq.en-gb.html?label=<label>;sid=<sid>;" />
```

We see that the href separator is not consistent over time.

The regexes we're using are the following 
- `(\?.*label=)(.*)(;|&)` and we replace by `$1removed$3`
- `(\?.*sid=)(.*)(;|&)` and we replace by `$1removed$3`

For it to work, we should
1. replace all &amp; by &
2. replace by a fixed separator `$1removed&`

What do you think @MattiSG ?

**Comment by MattiSG** [comment]
Unless we make a more precise exploration of it, I'm in favour of removing entirely content instead of leaving `removed` markers. Snapshots are there to track the original content. Versions should be clean; what if we introduce a new bug or redirect to another page by adding the `removed` marker?

The issue here is to use a regex instead of a filter that parses the URL, removes the unwanted parameters, and then stringifies it back. I know @clementbiron implemented this in a few declarations in France, and that this seems to be so recurring I'd be in favour of making it available in a declarable way. This could be a new RFC 🙂

**Comment by martinratinaud** [comment]
This will not change the problem as there is always ; and & alternating

So if I understand correctly, your idea is to remove all query params, right?

**Comment by MattiSG** [comment]
If I understand correctly, if the separator is `&` then `sid` and `label` will be two separate query params according to standard DOM parsing; if the separator is `;` then `sid` and `label` will be one single query param (the name of which being the first to be written) according to standard DOM parsing.

If that is correct, then in both cases, if we erase both `sid` and `label` from the URL, we should remove both, no matter their order nor separators 🙂

**Comment by clementbiron** [comment]
I used a function to remove query params in the [Facebook filters](https://github.com/OpenTermsArchive/france-elections-declarations/blob/main/declarations/Facebook.filters.js).

**Comment by martinratinaud** [comment]
Well I finally pushed something that works but it was crazily difficult.

- content changes overfetching 1. `&`, 2. `&amp;`, 3. `;`
- When the above is solved, using `URLSearchParams` is re-encoding all not encoded strings, leading to differences in the versions

I believe this is good enough now.
